### ISSUE TITLE
Cursor index mismatch

### ISSUE THREAD

**Issue by andriths** [ThorRafnar/TextEditor#1]
Reproduction:
Write a short line, and under it a longer line. move the cursor to the end of the long line, and press the up arrow to move back to the short line.
Press backspace, and the program will crash.
if you press the left arrow button, it will eventually reach the correct index and fix itself.

Fix:
in line_manager.py

    def try_move_down(self):
        # Move cursor down
        if self.cursor_line.next is not None:
            self.cursor_line = self.cursor_line.next
            self.cursor_line_index = max(min(self.cursor_line_index, len(self.cursor_line)-1), 0)

    def try_move_up(self):
        # Move cursor up
        if self.cursor_line.prev is not None:
            self.cursor_line = self.cursor_line.prev
            self.cursor_line_index = max(min(self.cursor_line_index, len(self.cursor_line)-1), 0)

**Comment by ThorRafnar** [comment]
Fixed. The fix is located in try_move_left and try_move_right.

The reason I did not use this fix is to preserve index when navigating from a long line down to a short line back to a long line. In most text editors the expected behaviour is that horizontal index stays consistent during vertical navigation until horizontal navigation and/or edits.
